import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';

const sans = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['200', '400', '700'],
});

export const metadata: Metadata = {
  title: 'tripin',
  description: 'Generated by Ninni Park',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sans.className}>{children}</body>
    </html>
  );
}
